name: Deploy

on:
    workflow_dispatch: {}

    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/deploy.yml"

concurrency:
    group: ${{ github.ref }}-deploy
    cancel-in-progress: false

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Generate creds.json
              run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json

            - name: Push Data
              uses: koenrh/dnscontrol-action@v3
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              with:
                  args: push
                  config_file: "scripts/dns.js"
