name: Publish

on:
    push:
        branches: [main]
        paths:
            - "domains/**"
            - ".github/workflows/deploy.yml"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-publish
    cancel-in-progress: false

jobs:
    dns:
        name: DNS
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - run: echo '{"cloudflare":{"TYPE":"CLOUDFLAREAPI","apitoken":"$CLOUDFLARE_API_TOKEN"}}' > ./creds.json

            - name: Publish
              uses: koenrh/dnscontrol-action@v3
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
              with:
                  args: push
                  config_file: "scripts/dns.js"
